<a href="https://colab.research.google.com/github/VineethInturi/VINEETH_MINI-PROJECT/blob/master/VINEETH_MINI_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
match_data = pd.read_csv('/content/drive/My Drive/deliveries.csv')
match_data


match_id  inning  ... dismissal_kind  fielder
0              1       1  ...            NaN      NaN
1              1       1  ...            NaN      NaN
2              1       1  ...            NaN      NaN
3              1       1  ...            NaN      NaN
4              1       1  ...            NaN      NaN
...          ...     ...  ...            ...      ...
150455       636       2  ...            NaN      NaN
150456       636       2  ...        run out  NV Ojha
150457       636       2  ...            NaN      NaN
150458       636       2  ...            NaN      NaN
150459       636       2  ...            NaN      NaN

[150460 rows x 21 columns]

In [ ]:
print(match_data.keys())

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')


In [ ]:
print(match_data['match_id'])

0           1
1           1
2           1
3           1
4           1
         ... 
150455    636
150456    636
150457    636
150458    636
150459    636
Name: match_id, Length: 150460, dtype: int64


In [ ]:
x1 = match_data.iloc[0:10023,11:17].values
print(x1)
y1 = match_data.iloc[0:10023,17].values
print(y1)



[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 4 0]
 ...
 [0 0 0 0 2 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]]
[0 0 4 ... 2 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1,test_size = 0.1,random_state = 10)  
print(x1_train.shape)
print(x1_test.shape)

(9020, 6)
(1003, 6)


In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x1_train,y1_train) 
y1_pred = model.predict(x1_test)
y1_pred  

array([5.55111512e-15, 5.55111512e-15, 4.00000000e+00, ...,
       5.55111512e-15, 1.00000000e+00, 1.00000000e+00])

In [ ]:
y1_test

array([0, 0, 4, ..., 0, 1, 1])

In [ ]:
from sklearn import metrics
metrics.mean_absolute_error(y1_test,y1_pred)

4.905791071922925e-15

In [ ]:
metrics.r2_score(y1_test,y1_pred)

1.0